[package]

name = "entity-component-system"
version = "0.0.1"
authors = ["Mark Schifflin <rschifflin@hotmail.com>"]

[dependencies.pubsub]

git = "https://github.com/rschifflin/rust-pubsub"

[dependencies.component_store]

git = "https://github.com/rschifflin/rust-component-store"
